import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.VITE_SUPABASE_URL
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Faltan VITE_SUPABASE_URL y/o VITE_SUPABASE_ANON_KEY en el entorno')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseAnonKey)

const seedData = [
  { nombre: 'María', apellido: 'González', dni: '30123456', email: 'maria.gonzalez@gmail.com', celular: '3815551001', ciudad_salida: 'tucuman', aeropuerto_salida: 'TUC - Teniente General Benjamín Matienzo', destino: 'brasil', destinos: ['brasil'], tipo_fecha: 'exacta', fecha_salida: '2026-07-15', fecha_regreso: '2026-07-25', adultos: 2, ninos_2_12: 1, bebes_0_2: 0, preferencias: ['vuelo_hotel', 'all_inclusive', 'traslados'], comentarios: 'Preferimos hotel frente al mar en Florianópolis', tipo_viaje: 'vacaciones', estado: 'nuevo' },
  { nombre: 'Carlos', apellido: 'López', dni: '27123456', email: 'carlos.lopez@hotmail.com', celular: '3815551002', ciudad_salida: 'tucuman', aeropuerto_salida: 'TUC - Teniente General Benjamín Matienzo', destino: 'caribe', destinos: ['caribe'], tipo_fecha: 'flexible', rango_fecha_inicio: '2026-08-01', rango_fecha_fin: '2026-08-15', adultos: 2, preferencias: ['vuelo_hotel', 'all_inclusive'], comentarios: 'Buscamos todo incluido en Punta Cana', tipo_viaje: 'luna_de_miel', estado: 'nuevo' },
  { nombre: 'Ana', apellido: 'Martínez', dni: '33456789', email: 'ana.martinez@outlook.com', celular: '3815551003', ciudad_salida: 'buenos_aires', aeropuerto_salida: 'EZE - Ministro Pistarini', destino: 'europa', destinos: ['europa'], tipo_fecha: 'exacta', fecha_salida: '2026-09-10', fecha_regreso: '2026-09-24', adultos: 1, preferencias: ['solo_vuelos', 'asistencia_viajero'], comentarios: 'Viaje solo a Madrid y París, necesito vuelos', tipo_viaje: 'vacaciones', estado: 'nuevo' },
  { nombre: 'Pedro', apellido: 'Sosa', dni: '28987654', email: 'pedro.sosa@yahoo.com', celular: '3815551004', ciudad_salida: 'cordoba', aeropuerto_salida: 'COR - Ingeniero Ambrosio Taravella', destino: 'estados_unidos', destinos: ['estados_unidos', 'disney'], tipo_fecha: 'mes', mes_preferido: 'Octubre', adultos: 2, ninos_2_12: 2, preferencias: ['vuelo_hotel', 'excursiones', 'traslados'], comentarios: 'Familia con dos hijos, queremos Orlando y Disney', tipo_viaje: 'familia', estado: 'nuevo' },
  { nombre: 'Laura', apellido: 'Fernández', dni: '31234567', email: 'laura.fernandez@gmail.com', celular: '3815551005', ciudad_salida: 'salta', aeropuerto_salida: 'SLA - Martín Miguel de Güemes', destino: 'mexico', destinos: ['mexico'], tipo_fecha: 'exacta', fecha_salida: '2026-11-20', fecha_regreso: '2026-11-30', adultos: 2, preferencias: ['vuelo_hotel', 'all_inclusive'], comentarios: 'Todo incluido en Cancún para luna de miel', tipo_viaje: 'luna_de_miel', estado: 'contactado' },
  { nombre: 'Jorge', apellido: 'Ramírez', dni: '25789123', email: 'jorge.ramirez@gmail.com', celular: '3815551006', ciudad_salida: 'rosario', aeropuerto_salida: 'ROS - Islas Malvinas', destino: 'disney', destinos: ['disney'], tipo_fecha: 'flexible', rango_fecha_inicio: '2027-01-05', rango_fecha_fin: '2027-01-20', adultos: 2, ninos_2_12: 3, bebes_0_2: 1, preferencias: ['vuelo_hotel', 'excursiones', 'asistencia_viajero'], comentarios: 'Viaje familiar con 3 niños, presupuesto para 7-10 días', tipo_viaje: 'familia', estado: 'contactado' },
  { nombre: 'Sofía', apellido: 'Díaz', dni: '34567890', email: 'sofia.diaz@hotmail.com', celular: '3815551007', ciudad_salida: 'mendoza', aeropuerto_salida: 'MDZ - El Plumerillo', destino: 'cruceros', destinos: ['cruceros'], tipo_fecha: 'exacta', fecha_salida: '2026-12-05', fecha_regreso: '2026-12-15', adultos: 2, preferencias: ['crucero', 'all_inclusive', 'excursiones'], comentarios: 'Crucero por el Mediterráneo, cabina con balcón', tipo_viaje: 'vacaciones', estado: 'cotizado' },
  { nombre: 'Diego', apellido: 'Torres', dni: '28123456', email: 'diego.torres@gmail.com', celular: '3815551008', ciudad_salida: null, aeropuerto_salida: null, destino: 'brasil', destinos: ['brasil'], destino_personalizado: 'Río de Janeiro', tipo_fecha: 'mes', mes_preferido: 'Febrero', adultos: 4, preferencias: ['vuelo_hotel', 'excursiones'], comentarios: 'Grupo de 4 amigos para carnaval de Río', tipo_viaje: 'aventura', estado: 'cotizado' },
  { nombre: 'Valentina', apellido: 'Castillo', dni: '36123456', email: 'valentina.castillo@gmail.com', celular: '3815551009', ciudad_salida: 'buenos_aires', aeropuerto_salida: 'EZE - Ministro Pistarini', destino: 'europa', destinos: ['europa'], tipo_fecha: 'exacta', fecha_salida: '2026-07-01', fecha_regreso: '2026-07-15', adultos: 1, preferencias: ['solo_vuelos', 'asistencia_viajero'], comentarios: 'Backpacking por Italia, solo vuelos', tipo_viaje: 'aventura', estado: 'nuevo' },
  { nombre: 'Roberto', apellido: 'Mendoza', dni: '30456789', email: 'roberto.mendoza@yahoo.com', celular: '3815551010', ciudad_salida: 'cordoba', aeropuerto_salida: 'COR - Ingeniero Ambrosio Taravella', destino: 'punta_cana', destinos: ['punta_cana'], tipo_fecha: 'flexible', rango_fecha_inicio: '2026-10-10', rango_fecha_fin: '2026-10-20', adultos: 2, ninos_2_12: 1, preferencias: ['all_inclusive', 'traslados', 'excursiones'], comentarios: 'Todo incluido preferiblemente en Bahía Príncipe', tipo_viaje: 'familia', estado: 'nuevo' },
  { nombre: 'Florencia', apellido: 'Paz', dni: '33123456', email: 'florencia.paz@hotmail.com', celular: '3815551011', ciudad_salida: null, aeropuerto_salida: null, destino: 'caribe', destinos: ['caribe'], tipo_fecha: 'exacta', fecha_salida: '2026-08-20', fecha_regreso: '2026-08-27', adultos: 2, preferencias: ['vuelo_hotel', 'all_inclusive'], comentarios: 'Semana en Jamaica, todo incluido', tipo_viaje: 'romantico', estado: 'reservado' },
  { nombre: 'Gustavo', apellido: 'Acosta', dni: '26678901', email: 'gustavo.acosta@gmail.com', celular: '3815551012', ciudad_salida: 'rosario', aeropuerto_salida: 'ROS - Islas Malvinas', destino: 'mexico', destinos: ['mexico'], tipo_fecha: 'exacta', fecha_salida: '2026-11-01', fecha_regreso: '2026-11-08', adultos: 2, bebes_0_2: 1, preferencias: ['all_inclusive'], tipo_viaje: 'vacaciones', estado: 'reservado' },
  { nombre: 'Camila', apellido: 'Vega', dni: '35123456', email: 'camila.vega@outlook.com', celular: '3815551013', ciudad_salida: 'tucuman', aeropuerto_salida: 'TUC - Teniente General Benjamín Matienzo', destino: 'disney', destinos: ['disney'], tipo_fecha: 'flexible', rango_fecha_inicio: '2027-03-15', rango_fecha_fin: '2027-03-30', adultos: 2, ninos_2_12: 2, preferencias: ['vuelo_hotel', 'excursiones', 'asistencia_viajero', 'traslados'], comentarios: 'Paquete completo Disney Orlando con parques', tipo_viaje: 'familia', estado: 'contactado' },
  { nombre: 'Luciano', apellido: 'Rivas', dni: '29456789', email: 'luciano.rivas@gmail.com', celular: '3815551014', ciudad_salida: 'buenos_aires', aeropuerto_salida: 'EZE - Ministro Pistarini', destino: 'otro', destinos: ['otro'], destino_personalizado: 'Tailandia', tipo_fecha: 'exacta', fecha_salida: '2026-12-10', fecha_regreso: '2027-01-05', adultos: 1, preferencias: ['solo_vuelos', 'asistencia_viajero'], comentarios: 'Viaje de mochilero por Tailandia y Camboya', tipo_viaje: 'aventura', estado: 'nuevo' },
  { nombre: 'Elena', apellido: 'Suárez', dni: '32123456', email: 'elena.suarez@hotmail.com', celular: '3815551015', ciudad_salida: 'mendoza', aeropuerto_salida: 'MDZ - El Plumerillo', destino: 'brasil', destinos: ['brasil'], tipo_fecha: 'mes', mes_preferido: 'Enero', adultos: 2, preferencias: ['vuelo_hotel', 'excursiones'], comentarios: 'Queremos conocer Salvador de Bahía', tipo_viaje: 'vacaciones', estado: 'cancelado' },
  { nombre: 'Federico', apellido: 'Luna', dni: '27890123', email: 'federico.luna@gmail.com', celular: '3815551016', ciudad_salida: 'tucuman', aeropuerto_salida: 'TUC - Teniente General Benjamín Matienzo', destino: 'europa', destinos: ['europa'], tipo_fecha: 'flexible', rango_fecha_inicio: '2026-09-01', rango_fecha_fin: '2026-09-20', adultos: 2, preferencias: ['vuelo_hotel', 'asistencia_viajero'], comentarios: 'Recorrido por varias ciudades europeas, presupuesto moderado', tipo_viaje: 'vacaciones', estado: 'cotizado' },
  { nombre: 'Martina', apellido: 'Peralta', dni: '37234567', email: 'martina.peralta@gmail.com', celular: '3815551017', ciudad_salida: 'cordoba', aeropuerto_salida: 'COR - Ingeniero Ambrosio Taravella', destino: 'punta_cana', destinos: ['punta_cana'], tipo_fecha: 'exacta', fecha_salida: '2026-10-25', fecha_regreso: '2026-11-01', adultos: 2, preferencias: ['all_inclusive', 'excursiones'], comentarios: 'Viaje de egresados, grupo de 15 personas', tipo_viaje: 'egresados', estado: 'nuevo' },
  { nombre: 'Hernán', apellido: 'Cáceres', dni: '26123456', email: 'hernan.caceres@yahoo.com', celular: '3815551018', ciudad_salida: 'salta', aeropuerto_salida: 'SLA - Martín Miguel de Güemes', destino: 'estados_unidos', destinos: ['estados_unidos'], tipo_fecha: 'exacta', fecha_salida: '2026-12-20', fecha_regreso: '2026-12-30', adultos: 3, preferencias: ['vuelo_hotel', 'traslados'], comentarios: 'Año nuevo en Nueva York, presupuesto para 3 adultos', tipo_viaje: 'vacaciones', estado: 'reservado' },
  { nombre: 'Gabriela', apellido: 'Moreno', dni: '31678901', email: 'gabriela.moreno@hotmail.com', celular: '3815551019', ciudad_salida: 'rosario', aeropuerto_salida: 'ROS - Islas Malvinas', destino: 'caribe', destinos: ['caribe'], tipo_fecha: 'mes', mes_preferido: 'Mayo', adultos: 2, preferencias: ['all_inclusive'], comentarios: 'Aniversario de bodas, buscamos algo romántico', tipo_viaje: 'romantico', estado: 'nuevo' },
  { nombre: 'Santiago', apellido: 'Roldán', dni: '28901234', email: 'santiago.roldan@gmail.com', celular: '3815551020', ciudad_salida: 'buenos_aires', aeropuerto_salida: 'EZE - Ministro Pistarini', destino: 'mexico', destinos: ['mexico'], tipo_fecha: 'flexible', rango_fecha_inicio: '2027-02-01', rango_fecha_fin: '2027-02-15', adultos: 2, preferencias: ['solo_vuelos', 'asistencia_viajero'], comentarios: 'Buscamos vuelos baratos a Ciudad de México', tipo_viaje: 'negocios', estado: 'cancelado' },
]

const { data, error } = await supabase.from('travel_quotes').insert(seedData).select()

if (error) {
  console.error('Error al insertar seed data:', error.message)
  process.exit(1)
}

console.log(`✓ ${data.length} registros insertados correctamente en travel_quotes`)
console.log('IDs:', data.map(r => r.id).join(', '))
